# List of Abbreviations {.unnumbered .unlisted}

**AC** — Alternating Current  
**AVDD** — Analog Supply Voltage  
**AVSS** — Analog Ground

**DC** — Direct Current  

**EDA** — Electronic Design Automation  
**EDA-OS** — Open-Source Electronic Design Automation  
**ESD** — Electrostatic Discharge  

**Hz** — Hertz  

**I/O** — Input/Output  
**IC** — Integrated Circuit  

**LED** — Light-Emitting Diode  
**LDO** — Low-Dropout Regulator  
**LHS** — Left-Hand Side  

**MC** — Monte-Carlo Simulation  
**MIM** — Metal–Insulator–Metal Capacitor   
**MOSFET** — Metal–Oxide–Semiconductor Field-Effect Transistor  
**MPW** — Multi-Project Wafer  
**µm** — Micrometre (Micron)  

**OTA** — Operational Transconductance Amplifier  

**PCB** — Printed Circuit Board  
**PMOS** — p-channel MOSFET  
**PSRR** — Power Supply Rejection Ratio  
**PVT** — Process, Voltage, Temperature  

**R** — Resistance  
**$R_{sub}$** — Substrate Resistance  
**$R_{well}$** — Well Resistance    
 
**SG13G2** — IHP 130-nm SiGe BiCMOS Technology  
**SME** — Small and Medium-Sized Enterprise  

**TT** — Typical–Typical Process Corner  

**V** — Volt  
**$V_{DS}$** — Drain–Source Voltage  
**$V_{GS}$** — Gate–Source Voltage  
**$V_{IN}^{+}$** — Non-inverting Input Voltage  
**$V_{IN}^{−}$** — Inverting Input Voltage  
**$V_{OUT}$** — Output Voltage  
**$V_{REF}$** — Reference Voltage  

**W** — Channel Width  
**W/L** — Width-to-Length Ratio  
